# Generated by Django 2.1.5 on 2019-01-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DT_ACCDN', models.CharField(max_length=30)),
                ('NO_CIVIQ_ACCDN', models.IntegerField()),
                ('RUE_ACCDN', models.CharField(max_length=30)),
                ('CD_GENRE_ACCDN', models.IntegerField()),
                ('NB_VEH_IMPLIQUES_ACCDN', models.IntegerField()),
                ('NB_MORTS', models.IntegerField()),
                ('NB_BLESSES_Sevre', models.IntegerField()),
                ('NB_BLESSES_LEGERS', models.IntegerField()),
                ('HEURE_ACCDN', models.CharField(max_length=30)),
                ('NB_VICTIMES_TOTAL', models.IntegerField()),
                ('GRAVITE', models.CharField(max_length=30)),
                ('nb_automobile_camion_leger', models.IntegerField()),
                ('nb_camionLourd_tractRoutier', models.IntegerField()),
                ('nb_outil_equipement', models.IntegerField()),
                ('nb_tous_autobus_minibus', models.IntegerField()),
                ('nb_bicyclette', models.IntegerField()),
                ('nb_cyclomoteur', models.IntegerField()),
                ('nb_motocyclette', models.IntegerField()),
                ('nb_taxi', models.IntegerField()),
                ('nb_urgence', models.IntegerField()),
                ('nb_motoneige', models.IntegerField()),
                ('nb_VHR', models.IntegerField()),
                ('nb_autres_types', models.IntegerField()),
                ('nb_veh_non_precise', models.IntegerField()),
                ('NB_DECES_PIETON', models.IntegerField()),
                ('NB_BLESSES_PIETON', models.IntegerField()),
                ('NB_VICTIMES_PIETON', models.IntegerField()),
                ('NB_DECES_MOTO', models.IntegerField()),
                ('NB_BLESSES_MOTO', models.IntegerField()),
                ('NB_VICTIMES_MOTO', models.IntegerField()),
                ('NB_DECES_VELO', models.IntegerField()),
                ('NB_BLESSES_VELO', models.IntegerField()),
                ('NB_VICTIMES_VELO', models.IntegerField()),
                ('LOC_LONG', models.DecimalField(decimal_places=7, max_digits=10)),
                ('LOC_LAT', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
    ]
