# Generated by Django 2.1.5 on 2019-01-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20190127_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='LOC_LAT',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='LOC_LONG',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='NB_BLESSES_MOTO',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='NB_BLESSES_PIETON',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='NB_BLESSES_VELO',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='NB_DECES_MOTO',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='NB_DECES_PIETON',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='NB_DECES_VELO',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='NB_VICTIMES_MOTO',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='NB_VICTIMES_PIETON',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='NB_VICTIMES_VELO',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='nb_VHR',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='nb_autres_types',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='nb_bicyclette',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='nb_cyclomoteur',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='nb_motocyclette',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='nb_motoneige',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='nb_taxi',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='nb_urgence',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='nb_veh_non_precise',
        ),
    ]
