# Generated by Django 2.1.5 on 2019-01-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20190127_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='GRAVITE',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='HEURE_ACCDN',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='NB_BLESSES_LEGERS',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='NB_BLESSES_Sevre',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='NB_VICTIMES_TOTAL',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='nb_automobile_camion_leger',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='nb_camionLourd_tractRoutier',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='nb_outil_equipement',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='nb_tous_autobus_minibus',
        ),
    ]
