# Generated by Django 2.1.5 on 2019-01-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20190127_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='CD_GENRE_ACCDN',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='NB_MORTS',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='NB_VEH_IMPLIQUES_ACCDN',
        ),
    ]
